### ISSUE TITLE
[Bug] Incorrectly specifying a region causes "Request unauthorized" error

### ISSUE THREAD

**Issue by atsui-bay1** [temporalio/terraform-provider-temporalcloud#107]
### What are you really trying to do?
Create a namespace

### Describe the bug
If the region is specified slightly incorrectly (i.e. `aws-us-east1` instead of `aws-us-east-1`), the error below is shown:
```
│ Error: Failed to create namespace
│ 
│   on temporal.tf line 47, in resource "temporalcloud_namespace" "namespace":
│   47: resource "temporalcloud_namespace" "namespace" {
│ 
│ rpc error: code = PermissionDenied desc = Request unauthorized
```
This is very confusing as it has nothing to do with authentication.  Note that some other misspellings produce a useful error message, such as `us-west-2` (without the `aws-`)
```
│ Error: Failed to create namespace
│ 
│   on temporal.tf line 47, in resource "temporalcloud_namespace" "namespace":
│   47: resource "temporalcloud_namespace" "namespace" {
│ 
│ rpc error: code = InvalidArgument desc = invalid region: us-west-2
```

### Minimal Reproduction
```
resource "temporalcloud_namespace" "namespace" {
  name     = "my-namespace"
  regions  = ["aws-us-east1"]
  accepted_client_ca =base64encode("<my_cert.pem>")
  retention_days     = 90
}
```

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux] Linux and Mac
- Temporal Version: [e.g. 1.14.0?] Terraform Provider 0.0.9
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by anekkanti** [comment]
This was fixed around Aug 14th. 
Now if the region is not valid, the back end throws back an error:
`region "%s" not found, invoke 'GetRegions' operation to list all available namespaces`
