### ISSUE TITLE
[Bug] Adding a user to multi namespaces seems to re-create the user each time and not just give them read access 

### ISSUE THREAD

**Issue by tony-powell-sp** [temporalio/terraform-provider-temporalcloud#119]
### What are you really trying to do?
Create a user and assign to a namespace with a defined role so this is managed through code but each time it appears to re-create the user and they only have access to last namespace created.  

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux] Mac running Terraform 
- Temporal Version: [e.g. 1.14.0?] and/or SDK version terraform provider 0.0.11
- Are you using Docker or Kubernetes or building Temporal from source? --- NO

**Comment by rohitgup14** [comment]
@swgillespie Can I close this issue ?

**Comment by jlacefie** [comment]
This should be resolved with the solution for #109

**Comment by jlacefie** [comment]
@tony-powell-sp we're struggling to recreate this scenario.  Do you have more details or ways we can reproduce.

**Comment by jlacefie** [comment]
document as side-effect and behavior of the current underlying API.  Also, recommend this is not best practice for TF.

**Comment by jlacefie** [comment]
docs addressed by #192

**Comment by jlacefie** [comment]
also addressed by the Temporal docs PR https://github.com/temporalio/documentation/pull/3219

**Comment by tony-powell-sp** [comment]
thanks @jlacefie I agree that terraform is not the best place but we have had issues trying to use the sdk to do the user management so we are just wanting to find a reliable method so that this is not a hand driven process and uniformity is across the environment!!

**Comment by tony-powell-sp** [comment]
glad you where able to re-create the condition :)

**Comment by jlacefie** [comment]
The first pass of this issue is resolved with [documentation](https://docs.temporal.io/production-deployment/cloud/terraform-provider#manage-temporal-cloud-users-with-terraform) guidance.
