### ISSUE TITLE
[Bug] temporalcloud_namespace_search_attribute can't be imported

### ISSUE THREAD

**Issue by swgillespie** [temporalio/terraform-provider-temporalcloud#133]
Due to the use of a UUID as the ID of a namespace search attribute (https://github.com/temporalio/terraform-provider-temporalcloud/blob/main/internal/provider/namespace_search_attribute_resource.go#L157
), they can't be imported. This resource should instead use its own name combined with the namespace ID that its attached to as the ID, so that the search attribute can be looked up on the namespace and imported.

**Comment by briankassouf** [comment]
This is fixed by #138. Please re-open if you're continuing to see issues
