### ISSUE TITLE
[Feature Request] Add user resource and namespaces data source

### ISSUE THREAD

**Issue by ennyjfrick** [temporalio/terraform-provider-temporalcloud#82]
### Is your feature request related to a problem? Please describe.

My company currently manages Temporal Cloud through a series of Python scripts that wrap around the `tcld` CLI. Being able to provision namespaces with IaC is great (and we're very grateful for the new provider!), but we're still stuck managing user permissions through the CLI, which is incredibly tedious and prone to breakage, especially if we need to give namespace permissions in bulk to users.

### Describe the solution you'd like

- A resource for Temporal Cloud users
- A datasource for namespaces

### Additional context

I wrote #83 which implements this

**Comment by swgillespie** [comment]
@ennyjfrick this is going out in the 0.0.6 release that's building now: https://github.com/temporalio/terraform-provider-temporalcloud/releases/tag/v0.0.6. thank you so much for contributing this! can we send you some Temporal stuff? 🎉

**Comment by ennyjfrick** [comment]
@swgillespie yeah, absolutely! pls shoot me an email!
