### ISSUE TITLE
Error when trying to change a CA in namespace

### ISSUE THREAD

**Issue by tony-powell-sp** [temporalio/terraform-provider-temporalcloud#90]
### What are you really trying to do?
If trying to change the location of a cert from a file to the secrets manager or reading from an enviromental variable it appends the new line the the exisiting cert and says it needs to change it but when it does that it gives an error nothing to do and the provider exits.  

### Describe the bug

Terraform plan says that cert has changed and it appends Cg== to the end of the exisiting and tries to change to the same without the Cg== and that gives an error.  

### Environment/Versions

- OS and processor: [e.g. M1 Mac, x86 Windows, Linux]
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- Are you using Docker or Kubernetes or building Temporal from source?

**Comment by swgillespie** [comment]
Thank you for the report! A fix for this has shipped in [v0.0.10](https://registry.terraform.io/providers/temporalio/temporalcloud/0.0.10).
